export const COMPANY_TYPES: string[] = [
  'IT / Software & Technology',
  'Artificial Intelligence / Machine Learning',
  'Data Science / Analytics',
  'Software Product / SaaS',
  'IT Services / Consulting',
  'Cybersecurity',
  'Cloud / DevOps',
  'Electronics & Semiconductors',
  'Embedded Systems',
  'Electrical & Electronics',
  'Industrial Automation & Control Systems',
  'IoT / Connected Technologies',
  'Robotics & Automation',
  'Engineering & Manufacturing',
  'Mechanical Engineering',
  'Automotive / Automobile',
  'Electric Vehicles / EV',
  'Aerospace & Aeronautical',
  'Defence & Space Technology',
  'Mechatronics',
  'Energy & Power',
  'Renewable Energy',
  'Oil & Gas',
  'Civil Engineering / Construction',
  'Infrastructure & Real Estate',
  'Chemical & Materials',
  'Pharmaceuticals',
  'Biotechnology / Life Sciences',
  'Medical Devices & Diagnostics',
  'Healthcare / HealthTech',
  'Research & Development',
  'Industrial Engineering',
  'Logistics & Supply Chain',
  'Banking & Financial Services',
  'FinTech',
  'Insurance',
  'FMCG / Consumer Goods',
  'Retail / E-commerce',
  'Food & Beverage',
  'Media / Advertising / Marketing',
  'Hospitality / Travel / Tourism',
  'HR / Recruitment / Staffing',
  'Management Consulting',
  'Business / Professional Services',
  'Others / Miscellaneous',
];
