const http = require('http');

function post(path, data, token = null) {
  return new Promise((resolve, reject) => {
    const postData = JSON.stringify(data);
    const headers = {
      'Content-Type': 'application/json',
      'Content-Length': Buffer.byteLength(postData),
    };
    if (token) {
      headers['Authorization'] = `Bearer ${token}`;
      headers['Cookie'] = `ipoms_auth_token=${token}`;
    }
    const req = http.request(
      {
        hostname: 'localhost',
        port: 5000,
        path,
        method: 'POST',
        headers,
      },
      (res) => {
        let body = '';
        res.on('data', (chunk) => (body += chunk));
        res.on('end', () => {
          try {
            resolve(JSON.parse(body));
          } catch (e) {
            resolve({ raw: body });
          }
        });
      }
    );
    req.on('error', reject);
    req.write(postData);
    req.end();
  });
}

async function run() {
  const mohanaLogin = await post('/api/v1/auth/login', {
    email: 'mohanaradha_a@infoziant.com',
    password: 'iPOMS@123',
  });
  console.log('Mohanaradha login success:', mohanaLogin.success, mohanaLogin.data?.user?.full_name);
  const token = mohanaLogin.data?.access_token || mohanaLogin.data?.token;
  const mohanaId = mohanaLogin.data?.user?._id;

  const res = await post('/api/v1/reports/generate', {
    template_type: 'month_end',
    college_id: 'ACET',
    coordinator_id: mohanaId,
    week_label: 'August 2026',
  }, token);

  if (res.success && res.data?.report) {
    const report = res.data.report;
    console.log('\n--- MONTH-END REPORT METADATA (MOHANARADHA) ---');
    console.log('Generated By (Prepared by):', report.generated_by);
    console.log('Branding Prepared By:', report.branding?.prepared_by);
    console.log('Confidential Notice:', report.branding?.confidential_notice);
  } else {
    console.error('Report generation error:', res);
  }
}

run().catch(console.error);
