const http = require('http');

function post(path, data, token = null) {
  return new Promise((resolve, reject) => {
    const postData = JSON.stringify(data);
    const headers = {
      'Content-Type': 'application/json',
      'Content-Length': Buffer.byteLength(postData),
    };
    if (token) {
      headers['Authorization'] = `Bearer ${token}`;
      headers['Cookie'] = `ipoms_auth_token=${token}`;
    }
    const req = http.request(
      {
        hostname: 'localhost',
        port: 5000,
        path,
        method: 'POST',
        headers,
      },
      (res) => {
        let body = '';
        res.on('data', (chunk) => (body += chunk));
        res.on('end', () => {
          try {
            resolve(JSON.parse(body));
          } catch (e) {
            resolve({ raw: body });
          }
        });
      }
    );
    req.on('error', reject);
    req.write(postData);
    req.end();
  });
}

async function run() {
  console.log('Testing Month-End report coordinator "Prepared by" naming...');
  
  const seshLogin = await post('/api/v1/auth/login', {
    email: 'Seshmitha_Tamil@icl.today',
    password: 'iPOMS@123',
  });
  console.log('Seshmitha login success:', seshLogin.success, seshLogin.data?.user?.full_name);
  const token = seshLogin.data?.access_token || seshLogin.data?.token;
  const seshId = seshLogin.data?.user?._id;

  const res = await post('/api/v1/reports/generate', {
    template_type: 'month_end',
    college_id: 'ACET',
    coordinator_id: seshId,
    week_label: 'August 2026',
  }, token);

  if (res.success && res.data?.report) {
    const report = res.data.report;
    console.log('\n--- MONTH-END REPORT METADATA ---');
    console.log('Title:', report.report_title);
    console.log('Period:', report.report_period);
    console.log('Generated By (Prepared by):', report.generated_by);
    console.log('Branding Prepared By:', report.branding?.prepared_by);
    console.log('Confidential Notice:', report.branding?.confidential_notice);
    console.log('Total Conversions KPI:', report.kpi_summary?.total_conversion_count);
    console.log('Companies Scheduled KPI:', report.kpi_summary?.total_companies_scheduled);
    console.log('Offers Received KPI:', report.kpi_summary?.total_offers_moved);
  } else {
    console.error('Report generation error:', res);
  }
}

run().catch(console.error);
